import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { getTheme, type ThemeMode } from "@tukka/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const mode = (typeof window !== 'undefined' && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') as ThemeMode;
  const themeVars = getTheme(mode);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={themeVars as React.CSSProperties}>
        {children}
      </body>
    </html>
  );
}
